### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by f8q8** [ssstk/LinkTokenPocket-ex#1]
操作系统：centos7.5
nodejs版本：v10.5.0
yarn：1.7.0
执行yarn dev的时候，报下面的错

yarn run v1.7.0
$ webpack --watch
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/data/LinkTokenPocket-ex/webpack.config.js:3:25)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ghost** [comment]
缺少依赖  查看错误信息
